services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: listening-app-base:latest
    command: tail -f /dev/null
    networks:
      - app_network

  main:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - HOST_IP=${HOST_IP}
      - LLM_MODEL=${LLM_MODEL}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL}
      - TTS_MODEL=${TTS_MODEL}
      - USE_GPU=${USE_GPU}
      - HUGGINGFACEHUB_API_TOKEN=${HUGGINGFACEHUB_API_TOKEN}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    depends_on:
      - otel-collector
      - prometheus
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/health']
      interval: 30s
      timeout: 10s
      retries: 3

  transcript-processor:
    build:
      context: ./services/transcript-processor
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - DB_PATH=/shared/data/app.db
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    depends_on:
      - otel-collector
    volumes:
      - shared_data:/shared/data
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5000/health']
      interval: 30s
      timeout: 10s
      retries: 3

  question-module:
    build:
      context: ./services/question-module
      dockerfile: Dockerfile
    ports:
      - '5001:5001'
    environment:
      - DB_PATH=/shared/data/app.db
      - LLM_MODEL=${LLM_MODEL}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    depends_on:
      - otel-collector
    volumes:
      - shared_data:/shared/data
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5001/health']
      interval: 30s
      timeout: 10s
      retries: 3

  audio-module:
    build:
      context: ./services/audio-module
      dockerfile: Dockerfile
    ports:
      - '5002:5002'
    environment:
      - DB_PATH=/shared/data/app.db
      - TTS_MODEL=${TTS_MODEL}
      - USE_GPU=${USE_GPU}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    depends_on:
      - otel-collector
    volumes:
      - shared_data:/shared/data
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5002/health']
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: korean-frontend
    ports:
      - '80:80'
    environment:
      - REACT_APP_API_BASE_URL=http://${HOST_IP:-localhost}:5000
      - REACT_APP_QUESTION_API_URL=http://${HOST_IP:-localhost}:5001
      - REACT_APP_AUDIO_API_URL=http://${HOST_IP:-localhost}:5002
    depends_on:
      - transcript-processor
      - question-module
      - audio-module
    networks:
      - app_network
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    ports:
      - '8008:11434'
    volumes:
      - ollama_data:/root/.ollama
    command: serve
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:11434/api/health']
      interval: 30s
      timeout: 10s
      retries: 3

  # ollama-server:
  #   image: ollama/ollama
  #   container_name: ollama-server
  #   ports:
  #     - '11434:11434'
  #   environment:
  #     - no_proxy=${NO_PROXY}
  #     - http_proxy=${HTTP_PROXY}
  #     - https_proxy=${HTTPS_PROXY}
  #     - LLM_MODEL=${LLM_MODEL}
  #   volumes:
  #     - ollama_data:/root/.ollama
  #     - ./start.sh:/start.sh
  #   entrypoint: ['/bin/bash', '/start.sh']
  #   networks:
  #     - app_network

  otel-collector:
    image: otel/opentelemetry-collector:latest
    volumes:
      - ./otel-config.yaml:/etc/otel-config.yaml
    command: ['--config=/etc/otel-config.yaml']
    ports:
      - '4317:4317'
    networks:
      - app_network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - '9090:9090'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - app_network
    restart: unless-stopped

volumes:
  shared_data:
  ollama_data:
    driver: local
  prometheus_data:

networks:
  app_network:
    driver: bridge
