global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']

  - job_name: 'services'
    static_configs:
      - targets: ['main:8000', 'transcript-processor:5000', 'question-module:5001', 'audio-module:5002']
