tools:
  web_search:
    description: >
      A tool that allows agents to perform web searches using DuckDuckGo.
    class: WebSearchAgent
    parameters:
      source: text
      region: wt-wt
      safesearch: moderate
      max_results: 5

  vector_db:
    description: >
      A tool that interacts with the Qdrant vector database for storing and retrieving vector embeddings.
    class: VectorDBTool
    parameters:
      db_url: "http://qdrant:6333"  # Updated to use container name
      collection_name: "korean_language_learning"
      embedding_dimension: 300
      max_results: 10