version: '3.8'

services:
  asl-web:
    build: .
    container_name: asl-web
    ports:
      - '8000:8000'
    volumes:
      - ./:/app
      - ./videos:/app/videos
    depends_on:
      - ollama
    networks:
      - asl-network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - '11434:11434'
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    networks:
      - asl-network

volumes:
  ollama-data:
    name: ollama-data

networks:
  asl-network:
    name: asl-network
