services:
  asl-web:
    build: .
    container_name: asl-web
    ports:
      - '5000:5000'
    volumes:
      - ./:/app
      - ../videos:/app/videos # Mount videos directory from parent folder
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  videos:
