services:
  ollama:
    image: ollama/ollama:latest
    container_name: hangul-ollama
    ports:
      - '11434:11434'
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hangul-web
    ports:
      - '5000:5000'
    volumes:
      - ./:/app # Mount the entire project directory
      - ./llava_output:/app/llava_output
    working_dir: /app # Set the working directory
    environment:
      - OLLAMA_HOST=http://ollama:11434
      # HuggingFace and ImgBB API credentials (these will be overridden by .env file)
      - IMGBB_API_KEY=${IMGBB_API_KEY}
      - HF_API_KEY=${HF_API_KEY}
      - HF_PROVIDER=${HF_PROVIDER:-hf}
      # Model configuration
      - MODEL_ID=${MODEL_ID:-llava-hf/llava-1.5-7b-hf}
      # Flask configuration
      - PORT=${PORT:-5000}
      - DEBUG=${DEBUG:-false}
    restart: unless-stopped
    depends_on:
      - ollama
    command: >
      bash -c "
        echo 'Starting server with API-based inference...' &&
        python server.py
      "

volumes:
  ollama_data:
